version: '3.2'
services:
  database:
    image: 278696104475.dkr.ecr.us-east-1.amazonaws.com/compstak/postgis:10-2.5
    ports:
      - 54320:5432
    volumes:
      - postgis:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: on-failure:5
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION:-0.9}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION:-0.9}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
    image: 278696104475.dkr.ecr.us-east-1.amazonaws.com/debezium/connect:${DEBEZIUM_VERSION:-0.9}
    ports:
      - 18083:8083
    links:
      - database
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses

networks:
  default:
volumes:
  postgis: